name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Static code analysis
      run: bash ./mvnw clean validate

    - name: Build & Test
      run: bash ./mvnw clean install
