name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Project
      run: bash setup-dev.sh

    - name: Static code analysis
      run: |
        ./mvnw clean validate

    - name: Build
      run: 
        echo "TODO"
        
    - name: Test
      run: 
        echo "TODO"
